[package]
name = "pal"
version = "0.1.0"
license = "BSD-2-Clause-Patent"
edition = "2021"

[features]
default = []
snp-emu = ["dep:tee-attestation-verification-lib"]
tdx = []

[dependencies]
zerocopy = { version = "0.8", features = ["derive"] }
log = "0.4"
tee-attestation-verification-lib = { git = "https://github.com/microsoft/TEE-Attestation-Verification", tag = "tav-1.0.2", features = ["crypto_pure_rust"], default-features = false, optional = true }
